services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/snapcram
    develop:
      watch:
        - action: restart
          target: /snapcram
          path: ./backend
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    env_file: ".env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10