services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/snapcram
    secrets:
      - jwt_secret
      - groq_api_key
    develop:
      watch:
        - action: restart
          target: /snapcram
          path: ./backend

secrets:
  groq_api_key:
    file: secrets/groq_api_key
  jwt_secret:
    file: secrets/jwt_secret
