services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/snapcram
    develop:
      watch:
        - action: restart
          target: /snapcram
          path: ./backend

secrets:
  groq_api_key:
    file: secrets/groq_api_key.txt
